import { Inter } from 'next/font/google'
import './globals.css'
import StyledComponentsRegistry from '@/lib/styled-component'
import "bootstrap/dist/css/bootstrap.min.css";
import dynamic from "next/dynamic";
import ImportBsJS from "@/lib/bootstrap-js";
import Layout from '@/components/Layout';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Book Library',
  description: 'Generated by create next app',
}

const DynamicBootstrap = dynamic(
  () => require("bootstrap/dist/js/bootstrap.min.js"),
  { ssr: false }
);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Layout>
        <ImportBsJS />
        {children}
        </Layout>
        </StyledComponentsRegistry>
        </body>
    </html>
  )
}
